apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-deploy
  labels:
    name: app-deploy
    app: app
spec:
   replicas: 3 # number of pods to run at any given time. Can be updated later
   selector:
    matchLabels:
      app: app
      type: mvc
   template:
    metadata:
      name: app-pod
      labels:   
          app: app
          type: mvc
    spec:
      containers:
        - name: app-pod
          image: toro1/aprotila:v1.0
          ports:
            - containerPort: 8080